- name: understand facts
  hosts: centos:ubuntu #all
  become: yes
  tasks: 
  - name: print all the facts
    ansible.builtin.debug:
      msg: "All Facts: {{ansible_facts}}"
    # Imagine if we don't have ansible user module
  - name: add user ubuntu
    ansible.builtin.command: adduser Krishna
    when: ansible_facts['distribution'] == "ubuntu"

  - name: add user centos
    ansible.builtin.command: useradd Krishna
    when: ansible_facts['distribution'] == "centos"